# Intro to pandas
### 27/01/2023

In [398]:
import numpy as np
from matplotlib import pyplot as plt
import pickle
import pandas as pd                   # If you don't have pandas installed, open your terminal and do
                                      # conda install -c conda-forge pickle

## Creating a pandas dataframe

In [379]:
df = pd.read_csv("11-data.csv")

## Peeking into your dataframe

In [380]:
df.head()

coord     z  M_black_hole        L_disk  magfield
0  0422.1+0211  2.27  7.940000e+08  3.980000e+46       2.2
1  1133.1+0033  1.63  5.010000e+09  2.510000e+46       1.4
2  0011.3+0054  1.49  6.030000e+08  3.020000e+45       1.6
3  1014.1+2306  0.57  3.980000e+08  6.030000e+45       2.0
4  1040.7+0614  1.26  1.000000e+09  6.030000e+46       2.2

In [212]:
df.tail(n=2)

coord     z  M_black_hole        L_disk  magfield
318  2357.8-5310  1.01  7.080000e+08  1.700000e+46       1.9
319  2358.2-1022  1.64  2.000000e+09  5.010000e+46       2.2

In [383]:
len(df)

320

In [384]:
df.columns

Index(['coord', 'z', 'M_black_hole', 'L_disk', 'magfield'], dtype='object')

By deafult, the first line of your CSV file is interpreted as the column names. But you can also name your columns yourself:

In [215]:
mynames = ['XY', 'Z', 'MBH', 'LD', 'B']
df2 = pd.read_csv("11-data.csv", names=mynames)
df2.head()

XY      Z           MBH         LD         B
0        coord      z  M_black_hole     L_disk  magfield
1  0422.1+0211   2.27      7.94e+08   3.98e+46      2.20
2  1133.1+0033   1.63      5.01e+09   2.51e+46      1.40
3  0011.3+0054   1.49      6.03e+08   3.02e+45      1.60
4  1014.1+2306   0.57      3.98e+08   6.03e+45      2.00

However, this way pandas interprets the first line as data and includes it as a line in your dataframe. In this case, we would loadthe table normally and rename the columns afterwards:

In [382]:
df3 = pd.read_csv("11-data.csv")
df3.columns = mynames
df3.head()

XY     Z           MBH            LD    B
0  0422.1+0211  2.27  7.940000e+08  3.980000e+46  2.2
1  1133.1+0033  1.63  5.010000e+09  2.510000e+46  1.4
2  0011.3+0054  1.49  6.030000e+08  3.020000e+45  1.6
3  1014.1+2306  0.57  3.980000e+08  6.030000e+45  2.0
4  1040.7+0614  1.26  1.000000e+09  6.030000e+46  2.2

## Working with columns

In [92]:
redshifts = df['z']
print(redshifts.head())

0    2.27
1    1.63
2    1.49
3    0.57
4    1.26
Name: z, dtype: float64


In [94]:
z_array = np.array(redshifts)
print(z_array.shape)

(320,)


We can add columns to a dataframe in a way similar to dictionaries:

In [102]:
b_array = np.array(df['magfield'])
magdensity_array = b_array ** 2 / (8 * np.pi) # New array of values

df["mag_density"] = magdensity_array # Add it to the table as a new column

df.head(2)

coord     z  M_black_hole        L_disk  magfield  mag_density
0  0422.1+0211  2.27  7.940000e+08  3.980000e+46       2.2     0.192577
1  1133.1+0033  1.63  5.010000e+09  2.510000e+46       1.4     0.077986

We can also select multiple columns:

In [249]:
df[['z','L_disk']].head()

z        L_disk
245  0.02  1.580000e+42
166  0.03  3.980000e+43
239  0.03  1.700000e+43
171  0.04  3.310000e+42
276  0.05  1.910000e+43

A dataframe can also be created from numpy arrays, interpreted as columns:

In [225]:
temp_dictionary = {"B" : b_array,
                   "u_B" : magdensity_array}
simplified_df = pd.DataFrame(temp_dictionary)
simplified_df.head(2)

B       u_B
0  2.2  0.192577
1  1.4  0.077986

In [226]:
# Remove ("drop") a column
more_simplified_df = simplified_df.drop(columns=["B"])
more_simplified_df.head()

u_B
0  0.192577
1  0.077986
2  0.101859
3  0.159155
4  0.192577

## Working with rows

In [345]:
df.head()

coord     z  M_black_hole        L_disk  magfield      sigma
245  1725.0+1152  0.02   501000000.0  1.580000e+42       0.1   0.632911
166  1104.4+3812  0.03   501000000.0  3.980000e+43       0.4   0.402010
239  1653.9+3945  0.03   501000000.0  1.700000e+43       0.1   0.058824
171  1136.6+7009  0.04   100000000.0  3.310000e+42       0.7  14.803625
276  2000.0+6509  0.05   501000000.0  1.910000e+43       0.5   1.308901

In [336]:
fifth_row = df.loc[4] # Locate and select 5th row
print(fifth_row)

coord                                                 1040.7+0614
z                                                            1.26
M_black_hole                                         1000000000.0
L_disk          60300000000000005240052764885508514749681238016.0
magfield                                                      2.2
sigma                                                    0.008027
Name: 4, dtype: object


What can we do with individual rows?

In [199]:
print("Coordinates:", df.loc[4][0])       # get the values by indexing with integers

print("Coordinates:", df.loc[4]['coord']) # get the values by indexing withcolumn names


myarray = np.array(df.loc[4]) # transform them into numpy arrays
print("Row as a numpy array:", myarray)


Coordinates: 1040.7+0614
Coordinates: 1040.7+0614
Row as a numpy array: ['1040.7+0614' 1.26 1000000000.0 6.030000000000001e+46 2.2
 0.19257748114119339]


`loc[4]` locates the row *labeled* `4` (by default, rows are labeled with integers starting from 0).

In this case, this corresponds to the row with index 4, which we can get with `iloc`:

In [202]:
df.iloc[4]

coord                                                 1040.7+0614
z                                                            1.26
M_black_hole                                         1000000000.0
L_disk          60300000000000005240052764885508514749681238016.0
magfield                                                      2.2
mag_density                                              0.192577
Name: 4, dtype: object

But this isn't always the case. Let's reorder the rows in the table:

In [227]:
df_sorted = df.sort_values('z')
df_sorted.head()

coord     z  M_black_hole        L_disk  magfield
245  1725.0+1152  0.02   501000000.0  1.580000e+42       0.1
166  1104.4+3812  0.03   501000000.0  3.980000e+43       0.4
239  1653.9+3945  0.03   501000000.0  1.700000e+43       0.1
171  1136.6+7009  0.04   100000000.0  3.310000e+42       0.7
276  2000.0+6509  0.05   501000000.0  1.910000e+43       0.5

In [392]:
df.index

RangeIndex(start=0, stop=320, step=1)

In [394]:
df_sorted.index

Int64Index([245, 166, 239, 171, 276, 220, 259, 247, 279,  42,
            ...
            161,  76, 132,  49, 127, 254,  64, 113,  88,   7],
           dtype='int64', length=320)

In [395]:
df_sorted.loc[245]

coord                                             1725.0+1152
z                                                        0.02
M_black_hole                                      501000000.0
L_disk          1580000000000000098773076915281004706398208.0
magfield                                                  0.1
Name: 245, dtype: object

In [396]:
df_sorted.iloc[0]

coord                                             1725.0+1152
z                                                        0.02
M_black_hole                                      501000000.0
L_disk          1580000000000000098773076915281004706398208.0
magfield                                                  0.1
Name: 245, dtype: object

`loc` can give you ranges and can be used simultaneously for rows and columns: 

In [343]:
df_sorted.loc[245:171, 'z':'L_disk']

z  M_black_hole        L_disk
245  0.02   501000000.0  1.580000e+42
166  0.03   501000000.0  3.980000e+43
239  0.03   501000000.0  1.700000e+43
171  0.04   100000000.0  3.310000e+42

Note how in this case, `245:171` doesn't have the usual meaning of "all integers between the two endpoints", but just "all rows between the row labeled `245` and that labeled `171`"

#### `loc` is extremely flexible and allows for all the numpy syntax you're used to.

Let's select all sources with redshift $z>2$:

In [372]:
df.loc[df['z'] > 2].head()

coord     z  M_black_hole        L_disk  magfield     sigma
84  0516.7-6207  2.02  1.700000e+08  2.190000e+45       1.8  0.147945
73  0438.8-4519  2.02  7.080000e+08  9.120000e+45       1.3  0.018531
93  0626.0-5436  2.05  6.030000e+08  3.020000e+46       2.0  0.013245
58  0325.5+2223  2.07  6.030000e+08  3.020000e+46       3.2  0.033907
86  0530.8+1330  2.07  1.000000e+09  1.820000e+47       2.0  0.002198

## Think-pair-share:

#### Consider the dimensionless quantity

$$
\sigma \equiv \frac{u_B}{u_\gamma} \approx 10^{44}\frac{B^2}{L_\mathrm{disk}}
$$

#### (in CGS units, as given in our table).

#### **Use our dataframe to find the coordinates of the 5 sources with highest values of $\sigma$**.

In [303]:
sigma = 1e44 * df['magfield'] ** 2 /  df['L_disk'] # First, we calculate an array of sigmas

print(f"Min sigma: {sigma.min():.3f}")             # ... and check if the values make sense
print(f"Max sigma: {sigma.max():.3f}")

Min sigma: 0.001
Max sigma: 87.113


In [305]:
df['sigma'] = sigma # Then we add the new column to our dataframe 
highest_sigma = df.sort_values('sigma').iloc[-5:]
highest_sigma.head()

coord     z  M_black_hole        L_disk  magfield      sigma
171  1136.6+7009  0.04   100000000.0  3.310000e+42       0.7  14.803625
266  1902.9-6745  0.25   200000000.0  7.080000e+43       3.5  17.302260
220  1517.6-2422  0.05   501000000.0  1.510000e+43       2.1  29.205298
42   0217.2+0837  0.09   501000000.0  1.200000e+43       2.0  33.333333
259  1806.7+6949  0.05    22900000.0  7.760000e+42       2.6  87.113402

In [307]:
# or...
highest_sigma = df.sort_values('sigma')[::-1].iloc[:5]
highest_sigma.head()

coord     z  M_black_hole        L_disk  magfield      sigma
259  1806.7+6949  0.05    22900000.0  7.760000e+42       2.6  87.113402
42   0217.2+0837  0.09   501000000.0  1.200000e+43       2.0  33.333333
220  1517.6-2422  0.05   501000000.0  1.510000e+43       2.1  29.205298
266  1902.9-6745  0.25   200000000.0  7.080000e+43       3.5  17.302260
171  1136.6+7009  0.04   100000000.0  3.310000e+42       0.7  14.803625

In [308]:
# Finally, the task was to get the source coordinates:
list(highest_sigma['coord'])

['1806.7+6949', '0217.2+0837', '1517.6-2422', '1902.9-6745', '1136.6+7009']

#### You also have a one-line solution (feel free to work through it):

In [351]:
list(df['coord'][sigma.sort_values()[::-1].iloc[:5].index]) # use these indices to index your dataframe

['1806.7+6949', '0217.2+0837', '1517.6-2422', '1902.9-6745', '1136.6+7009']